apiVersion: v2
name: vault-raft-snapshot-agent
description: vault-raft-snapshot-agent takes periodic snapshots of vault's raft database and writes it to a local file or an S3 bucket
keywords:
- vault-raft-snapshot-agent
- vault
- backup
- snapshots
- raft
- integrated storage


type: application
version: 0.1.0
appVersion: "v0.4.1"

home: https://github.com/Argelbargel/vault-raft-snapshot-agent
maintainers:
- name: Argelbargel
